# Generated by Django 2.2 on 2021-04-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribuyente',
            name='cuit',
        ),
        migrations.RemoveField(
            model_name='intermediario',
            name='cuit',
        ),
        migrations.AddField(
            model_name='intermediario',
            name='delanteDni',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='intermediario',
            name='dorsoDni',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
