# Generated by Django 2.2 on 2021-04-27 12:38

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0002_auto_20210427_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centrodereciclaje',
            name='cuit',
        ),
        migrations.AddField(
            model_name='centrodereciclaje',
            name='celular',
            field=phone_field.models.PhoneField(blank=True, help_text='Celular', max_length=31),
        ),
        migrations.AddField(
            model_name='centrodereciclaje',
            name='coordenadas',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centrodereciclaje',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intermediario',
            name='centro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecoinclusion.CentroDeReciclaje'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PuntoDeAcopio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadas', models.CharField(max_length=100)),
                ('tipoDeReciclado', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Secos'), ('2', 'Humedos'), ('3', 'Alumnio')], max_length=5)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoinclusion.CentroDeReciclaje')),
            ],
        ),
    ]
