# Generated by Django 2.2 on 2021-04-27 12:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0003_auto_20210427_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntodeacopio',
            name='tipoDeReciclado',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Secos'), ('2', 'Humedos'), ('3', 'Alumnio')], max_length=1),
        ),
    ]
