# Generated by Django 2.2 on 2021-05-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0004_auto_20210427_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodereciclaje',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
