# Generated by Django 2.2 on 2021-05-27 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0005_centrodereciclaje_verificado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centrodereciclaje',
            old_name='celular',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='centrodereciclaje',
            old_name='coordenadas',
            new_name='ubicacion',
        ),
    ]
