# Generated by Django 2.2 on 2021-05-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0006_auto_20210527_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodereciclaje',
            name='final_atencion',
            field=models.CharField(default='XD', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centrodereciclaje',
            name='inicio_atencion',
            field=models.CharField(default='XD', max_length=10),
            preserve_default=False,
        ),
    ]
