# Generated by Django 2.2 on 2021-05-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0007_auto_20210527_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrodereciclaje',
            name='final_atencion',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='centrodereciclaje',
            name='inicio_atencion',
            field=models.CharField(default='', max_length=10),
        ),
    ]
