# Generated by Django 2.2 on 2021-05-27 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0008_auto_20210527_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrodereciclaje',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
