# Generated by Django 2.2 on 2021-05-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0010_auto_20210527_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntodeacopio',
            name='tipoDeReciclado',
            field=models.CharField(max_length=100),
        ),
    ]
