# Generated by Django 2.2 on 2021-05-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0011_auto_20210528_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntodeacopio',
            old_name='coordenadas',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='puntodeacopio',
            name='ubicacion',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
