# Generated by Django 2.2 on 2021-05-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0012_auto_20210528_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intermediario',
            name='centro',
        ),
        migrations.AddField(
            model_name='intermediario',
            name='puntos',
            field=models.ManyToManyField(to='ecoinclusion.PuntoDeAcopio'),
        ),
    ]
