# Generated by Django 2.2 on 2021-05-28 02:10

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0013_auto_20210528_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intermediario',
            name='delanteDni',
        ),
        migrations.RemoveField(
            model_name='intermediario',
            name='dorsoDni',
        ),
        migrations.RemoveField(
            model_name='intermediario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='intermediario',
            name='diasRecoleccion',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intermediario',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intermediario',
            name='telefono',
            field=phone_field.models.PhoneField(blank=True, help_text='Celular', max_length=31),
        ),
    ]
