# Generated by Django 2.2 on 2021-05-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0014_auto_20210528_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermediario',
            name='centro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecoinclusion.CentroDeReciclaje'),
            preserve_default=False,
        ),
    ]
