# Generated by Django 2.2 on 2021-05-28 15:46

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0015_intermediario_centro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrodereciclaje',
            name='horarioFinal',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='centrodereciclaje',
            name='horarioInicio',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='centrodereciclaje',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='centrodereciclaje',
            name='telefono',
            field=phone_field.models.PhoneField(blank=True, help_text='Celular', max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='centrodereciclaje',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
