# Generated by Django 2.2 on 2021-06-21 18:48

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0016_auto_20210528_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centrodereciclaje',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='puntodeacopio',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='centrodereciclaje',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centrodereciclaje',
            name='long',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puntodeacopio',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puntodeacopio',
            name='long',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intermediario',
            name='diasRecoleccion',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'lunes'), ('2', 'martes'), ('3', 'miercoles'), ('4', 'jueves'), ('5', 'viernes'), ('6', 'sabado'), ('7', 'domingo')], max_length=13),
        ),
    ]
