# Generated by Django 2.2 on 2021-06-22 00:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0017_auto_20210621_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrodereciclaje',
            name='horarioFinal',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centrodereciclaje',
            name='horarioInicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intermediario',
            name='diasRecoleccion',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'lunes'), (2, 'martes'), (3, 'miercoles'), (4, 'jueves'), (5, 'viernes'), (6, 'sabado'), (7, 'domingo')], max_length=13),
        ),
    ]
