# Generated by Django 2.2 on 2021-06-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0018_auto_20210622_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodereciclaje',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
