# Generated by Django 2.2 on 2021-06-28 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0019_centrodereciclaje_horario_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centrodereciclaje',
            old_name='horarioFinal',
            new_name='horario_final',
        ),
        migrations.RemoveField(
            model_name='centrodereciclaje',
            name='horarioInicio',
        ),
    ]
