# Generated by Django 2.2 on 2021-06-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0021_auto_20210628_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntodeacopio',
            old_name='tipo_de_Reciclado',
            new_name='tipo_de_reciclado',
        ),
    ]
