# Generated by Django 2.2 on 2021-06-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0022_auto_20210628_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intermediario',
            old_name='diasRecoleccion',
            new_name='dias_disponibles',
        ),
    ]
