# Generated by Django 2.2 on 2021-06-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0023_auto_20210628_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='intermediario',
            name='dias_disponibles',
        ),
        migrations.AddField(
            model_name='intermediario',
            name='dias_disponibles',
            field=models.ManyToManyField(max_length=7, to='ecoinclusion.Dia'),
        ),
    ]
