# Generated by Django 2.2 on 2021-06-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0024_auto_20210628_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeReciclado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='puntodeacopio',
            name='tipo_de_reciclado',
        ),
        migrations.AddField(
            model_name='puntodeacopio',
            name='tipo_de_reciclado',
            field=models.ManyToManyField(to='ecoinclusion.TipoDeReciclado'),
        ),
    ]
