# Generated by Django 2.2 on 2021-06-29 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0025_auto_20210628_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntodeacopio',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='ecoinclusion.CentroDeReciclaje'),
        ),
    ]
