# Generated by Django 2.2 on 2021-06-29 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0026_auto_20210629_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermediario',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intermediarios', to='ecoinclusion.CentroDeReciclaje'),
        ),
    ]
