# Generated by Django 2.2 on 2021-08-31 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecoinclusion', '0028_auto_20210810_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('verificado', models.BooleanField(default=False)),
                ('punto_de_acopio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecoinclusion.PuntoDeAcopio')),
                ('tipo_de_reciclado', models.ManyToManyField(to='ecoinclusion.TipoDeReciclado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
