# Generated by Django 2.2 on 2021-08-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0029_deposito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposito',
            name='fecha',
            field=models.DateField(),
        ),
    ]
