# Generated by Django 2.2 on 2021-09-18 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0030_auto_20210831_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposito',
            name='centro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to='ecoinclusion.CentroDeReciclaje'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deposito',
            name='punto_de_acopio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecoinclusion.PuntoDeAcopio'),
        ),
        migrations.AlterField(
            model_name='deposito',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to=settings.AUTH_USER_MODEL),
        ),
    ]
