# Generated by Django 2.2 on 2021-09-19 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0035_auto_20210919_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantidadreciclado',
            name='tipo_de_reciclado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cantidades', to='ecoinclusion.TipoDeReciclado'),
        ),
    ]
