# Generated by Django 2.2 on 2021-09-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0038_auto_20210919_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantidadreciclado',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
