# Generated by Django 2.2 on 2021-09-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0040_auto_20210924_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrodereciclaje',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=21, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='centrodereciclaje',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=21, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='puntodeacopio',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=21, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='puntodeacopio',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=21, max_digits=24, null=True),
        ),
    ]
