# Generated by Django 2.2 on 2021-09-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0041_auto_20210924_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeyGoogleMaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
