# Generated by Django 2.2 on 2021-09-24 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0042_apikeygooglemaps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposito',
            name='punto_de_acopio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to='ecoinclusion.PuntoDeAcopio'),
        ),
    ]
