# Generated by Django 2.2 on 2021-09-24 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecoinclusion', '0043_auto_20210924_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrodereciclaje',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cooperativa', to=settings.AUTH_USER_MODEL),
        ),
    ]
